### ISSUE TITLE
File Manager integration not working

### ISSUE THREAD

**Issue by Suzie97** [marbetschar/Linux#1]
I installed the ppa and nextcloud-client using the commands you have mentioned. I also created the cloud-providers folder and the other two files.

But Nextcloud has not integrated with the file manager. There is no nextcloud option in the file manger network section.

**Comment by marbetschar** [comment]
Hi @Suzie97,

The Nextcloud item in the File Manager should appear, as soon as you configured your Nextcloud account. To do so, simply start the "Nextcloud desktop sync client" from the Applications menu in elementary and login to your Nextcloud server.

FWIW: The creation of the files mentioned in the Troubleshooting section should no longer be necessary, since the underlying bug has been fixed in the nextcloud-client.

Will close the issue, feel free to reopen if the problem persists.

**Comment by Suzie97** [comment]
I opened the Nextcloud client and logged in to my cloud provider account. It still didn't appear in the files app. 

Then I created the files mentioned in the trouble shooting section and it still does not work.

**Comment by marbetschar** [comment]
mhm, thats weird. Which version of elementary OS do you use? Can you post a screenshot of `System Settings > System > Operating System` and the output of `nextcloud --version` from your Terminal?

**Comment by Suzie97** [comment]
I am using Elementary 5.1.7 Hera

**Comment by Suzie97** [comment]
![image](https://user-images.githubusercontent.com/68198116/110454676-89a79d80-80ed-11eb-9b2e-95cb45a754d4.png)

**Comment by Suzie97** [comment]
I used to use the flatpak version of nextcloud desktop sync client. Before installing the ppa, I removed that flatpak.

But the configuration for the flatpak is still there. Is it related to this issue?

**Comment by marbetschar** [comment]
looks good to me, the needed fix is essentially in [nextcloud-desktop v2.6.3 ("Install libcloudproviders files by default on debian")](https://github.com/nextcloud/desktop/releases/tag/v2.6.3) - therefore you should be fine with the installed PPA version.

> But the configuration for the flatpak is still there. Is it related to this issue?

Maybe, but I'm not sure. Personally I always used the PPA version and after the fix was released, it worked every time on a fresh install on Hera. Can you try to completely uninstall Nextcloud on your box (Flatpak as well as Apt version), remove the files you created manually and do a fresh install from PPA?

If that still does not fix the problem, you might want to open an issue at [elementary/files](https://github.com/elementary/files) - maybe we are dealing with some sort of regression here. Unfortunately I can't help that much, because I'm already running the preview release of elementary 6 - and here the problem does not exist.

**Comment by Suzie97** [comment]
Ok thanks a lot for your time.
